package view;

import configuration.Exceptions.ActivityAlreadyAssignedException;
import configuration.Exceptions.DayNotValidException;
import configuration.Exceptions.InvalidParameterObjectException;
import configuration.Exceptions.TimeExpiredException;
import configuration.Exceptions.UnsuccessfulUpdateException;
import configuration.Exceptions.UsernotFoundException;
import controller.Services.ActivityService;
import controller.Services.CompetenceService;
import controller.Services.UserManagementService;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.RoundRectangle2D;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Competences.Competence;
import model.Users.UserModel;

/**
 *
 * @author Group9
 */
public class AssignmentActivity extends javax.swing.JFrame {

    private final int ID;
    private final double time;
    private final int week;
    private final String area;
    private final String type;

    private List<UserModel> listMaintainers = new LinkedList<>();
    private CompetenceService competence = CompetenceService.getCompetenceService();
    private UserManagementService user = UserManagementService.getUserManagementService();
    private List<Competence> skills = new LinkedList<>();
    private Map<String, List<Integer>> mapIdDays = new HashMap<>();
    private ActivityService activityService = ActivityService.getActivityService();
    
    /**
     * Creates new form AssignmentActivity
     * 
     * @param ID
     * @param area
     * @param type
     * @param time
     * @param week
     * @throws SQLException
     * @throws InvalidParameterObjectException 
     */
    public AssignmentActivity(int ID, String area, String type, double time, int week) throws SQLException, InvalidParameterObjectException {
        initComponents();
        this.ID = ID;
        this.week = week;
        this.area = area;
        this.type = type;
        this.time = time;
      
        jLabelInfo.setText(this.showInfo());
        jLabelWeek.setText(String.valueOf(week));
        jLabelCurrentWeek.setText(this.getCurrentWeek());
        
        ImageIcon icon = new ImageIcon("src/icons/app_icon.png");
        setIconImage(icon.getImage());
        setTitle("Maintenance System App");
        setSize(1344, 592);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        addComponentListener(new ComponentAdapter() {
               @Override
                public void componentResized(ComponentEvent e) {
                    setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
                }
        });
        
        showSkillsNeeded();
        getMaintainers();
        initMapIdDays();
        
        // Set cell colours for each column
        jTableMaintainersAvail.setDefaultRenderer(Object.class, new MyTableCellRenderer());
        for (int i = 2; i < jTableMaintainersAvail.getColumnCount(); i++) {
            this.changeTable(jTableMaintainersAvail, i);
        }
        
    }

    class MyTableCellRenderer extends DefaultTableCellRenderer {

        @Override
        public Color getBackground() {
            return super.getBackground();
        }
    }

    /**
     *This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaintainersAvail = new javax.swing.JTable();
        jLabelMaintainersAvail = new javax.swing.JLabel();
        jButtonAssign = new javax.swing.JButton();
        jLabelMinimize = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSkills = new javax.swing.JTable();
        jLabelInfo = new javax.swing.JLabel();
        jLabelCurrentWeek = new javax.swing.JLabel();
        jLabelActivityInfo = new javax.swing.JLabel();
        jLabelCurrentWeekNum = new javax.swing.JLabel();
        jCheckBoxMon = new javax.swing.JCheckBox();
        jCheckBoxTue = new javax.swing.JCheckBox();
        jCheckBoxWed = new javax.swing.JCheckBox();
        jCheckBoxThu = new javax.swing.JCheckBox();
        jCheckBoxFri = new javax.swing.JCheckBox();
        jCheckBoxSat = new javax.swing.JCheckBox();
        jCheckBoxSun = new javax.swing.JCheckBox();
        jLabelMon = new javax.swing.JLabel();
        jLabelTue = new javax.swing.JLabel();
        jLabelWed = new javax.swing.JLabel();
        jLabelFri = new javax.swing.JLabel();
        jLabelThu = new javax.swing.JLabel();
        jLabelSat = new javax.swing.JLabel();
        jLabelSun = new javax.swing.JLabel();
        jLabelSkills = new javax.swing.JLabel();
        jLabelTitleAct = new javax.swing.JLabel();
        jLabelTitleCheck = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jLabelWeek = new javax.swing.JLabel();
        jLabelWeekNum1 = new javax.swing.JLabel();
        jButtonAssigned = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabelTitle.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("ASSIGN ACTIVITY");

        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jLabelExit.setText("jLabel2");
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        jTableMaintainersAvail.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jTableMaintainersAvail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Skills", "Availab Mon", "Availab Tue", "Availab Wed", "Availab Thu", "Availab Fri", "Availab Sat", "Availab Sun"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMaintainersAvail);

        jLabelMaintainersAvail.setBackground(new java.awt.Color(255, 204, 0));
        jLabelMaintainersAvail.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelMaintainersAvail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMaintainersAvail.setText("Availability Maintainer");
        jLabelMaintainersAvail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 0), new java.awt.Color(255, 204, 0), null, null));
        jLabelMaintainersAvail.setOpaque(true);

        jButtonAssign.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonAssign.setText("Assign");
        jButtonAssign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssignMouseClicked(evt);
            }
        });

        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        jTableSkills.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jTableSkills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Skills"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableSkills);

        jLabelInfo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setFont(new java.awt.Font("Impact", 0, 17)); // NOI18N
        jLabelInfo.setOpaque(true);

        jLabelCurrentWeek.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCurrentWeek.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabelCurrentWeek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCurrentWeek.setOpaque(true);

        jLabelActivityInfo.setBackground(new java.awt.Color(255, 204, 0));
        jLabelActivityInfo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelActivityInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelActivityInfo.setText("Activity To Assign");
        jLabelActivityInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 0), new java.awt.Color(255, 204, 0), null, null));
        jLabelActivityInfo.setOpaque(true);

        jLabelCurrentWeekNum.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelCurrentWeekNum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCurrentWeekNum.setText("Current Week N°");

        jCheckBoxMon.setText("jCheckBox1");
        jCheckBoxMon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxMonStateChanged(evt);
            }
        });

        jCheckBoxTue.setText("jCheckBox2");
        jCheckBoxTue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxTueStateChanged(evt);
            }
        });

        jCheckBoxWed.setText("jCheckBox3");
        jCheckBoxWed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxWedStateChanged(evt);
            }
        });
        jCheckBoxWed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWedActionPerformed(evt);
            }
        });

        jCheckBoxThu.setText("jCheckBox4");
        jCheckBoxThu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxThuStateChanged(evt);
            }
        });

        jCheckBoxFri.setText("jCheckBox5");
        jCheckBoxFri.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxFriStateChanged(evt);
            }
        });

        jCheckBoxSat.setText("jCheckBox6");
        jCheckBoxSat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxSatStateChanged(evt);
            }
        });

        jCheckBoxSun.setText("jCheckBox7");
        jCheckBoxSun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxSunStateChanged(evt);
            }
        });
        jCheckBoxSun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSunActionPerformed(evt);
            }
        });

        jLabelMon.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelMon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMon.setText("Mon");

        jLabelTue.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTue.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTue.setText("Tue");

        jLabelWed.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelWed.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWed.setText("Wed");

        jLabelFri.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelFri.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFri.setText("Fri");

        jLabelThu.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelThu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelThu.setText("Thu");

        jLabelSat.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelSat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSat.setText("Sat");

        jLabelSun.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelSun.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSun.setText("Sun");

        jLabelSkills.setBackground(new java.awt.Color(255, 204, 0));
        jLabelSkills.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelSkills.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSkills.setText("Skills Needed");
        jLabelSkills.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 0), new java.awt.Color(255, 204, 0), null, null));
        jLabelSkills.setOpaque(true);

        jLabelTitleAct.setBackground(new java.awt.Color(255, 204, 0));
        jLabelTitleAct.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTitleAct.setText("To Assign Activity");
        jLabelTitleAct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 0), new java.awt.Color(255, 204, 0), null, null));
        jLabelTitleAct.setOpaque(true);

        jLabelTitleCheck.setBackground(new java.awt.Color(255, 204, 0));
        jLabelTitleCheck.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTitleCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleCheck.setText("Check Day");
        jLabelTitleCheck.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 0), new java.awt.Color(255, 204, 0), null, null));
        jLabelTitleCheck.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back_button.png"))); // NOI18N
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelBack)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelBack)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelWeek.setBackground(new java.awt.Color(255, 255, 255));
        jLabelWeek.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabelWeek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWeek.setOpaque(true);

        jLabelWeekNum1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelWeekNum1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWeekNum1.setText("Activity Week N°");

        jButtonAssigned.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonAssigned.setText("Go To Assigned Activities");
        jButtonAssigned.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssignedMouseClicked(evt);
            }
        });
        jButtonAssigned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignedActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(jLabelWeekNum1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                        .add(232, 232, 232))
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabelActivityInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabelWeek, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabelCurrentWeek, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabelTitleAct)
                                    .add(jLabelTitleCheck, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(60, 60, 60)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabelMon, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jCheckBoxMon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .add(57, 57, 57)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jCheckBoxTue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabelTue, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .add(49, 49, 49)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jLabelWed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jCheckBoxWed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .add(56, 56, 56)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jCheckBoxThu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabelThu, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .add(51, 51, 51)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jCheckBoxFri, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabelFri, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .add(55, 55, 55)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jCheckBoxSat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabelSat, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .add(63, 63, 63)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jCheckBoxSun, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabelSun, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .add(48, 48, 48))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabelSkills, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabelInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 287, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 765, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabelMaintainersAvail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 765, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonAssigned)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonAssign))
                                .add(12, 12, 12))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jLabelCurrentWeekNum)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabelTitle)
                                .add(526, 526, 526))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabelMinimize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelExit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(66, 66, 66)
                        .add(jLabelTitle)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabelTitleCheck)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabelMon)
                                        .add(jLabelTue)
                                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(jLabelThu)
                                            .add(jLabelWed))
                                        .add(jLabelFri)
                                        .add(jLabelSat)))
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabelTitleAct)
                                    .add(jCheckBoxMon)
                                    .add(jCheckBoxTue)
                                    .add(jCheckBoxWed)
                                    .add(jCheckBoxThu)
                                    .add(jCheckBoxFri)
                                    .add(jCheckBoxSat)
                                    .add(jCheckBoxSun))
                                .add(25, 25, 25))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .add(jLabelSun)
                                .add(48, 48, 48))))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabelExit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabelMinimize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                        .add(jLabelCurrentWeekNum)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelCurrentWeek, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabelWeekNum1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelWeek, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabelActivityInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabelMaintainersAvail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, 0)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonAssign, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(23, 23, 23)
                        .add(jButtonAssigned, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(jLabelInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabelSkills)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(83, 83, 83))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        setVisible(false);
        SelectActivity sActivity = new SelectActivity();
        sActivity.setVisible(true);
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jButtonAssignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssignMouseClicked

        // Avoid empty selections
        if (jTableMaintainersAvail.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Please, select a Maintainer first");
            return;
        }

        if (!jCheckBoxMon.isSelected() && !jCheckBoxTue.isSelected()
                && !jCheckBoxWed.isSelected() && !jCheckBoxThu.isSelected()
                && !jCheckBoxFri.isSelected() && !jCheckBoxSat.isSelected()
                && !jCheckBoxSun.isSelected()) {

            JOptionPane.showMessageDialog(null, "Please, select a day first");
            return;
        }

        try {
            // Get the selected maintainer
            int selectedIndex = jTableMaintainersAvail.getSelectedRow();
            DefaultTableModel users = (DefaultTableModel) jTableMaintainersAvail.getModel();

            String username = users.getValueAt(selectedIndex, 0).toString();

            List<Integer> listDays = new ArrayList<>();

            // Checking which day was selected
            if (jCheckBoxMon.isSelected()) {
                listDays.add(1);
            }
            if (jCheckBoxTue.isSelected()) {
                listDays.add(2);
            }
            if (jCheckBoxWed.isSelected()) {
                listDays.add(3);
            }
            if (jCheckBoxThu.isSelected()) {
                listDays.add(4);
            }
            if (jCheckBoxFri.isSelected()) {
                listDays.add(5);
            }
            if (jCheckBoxSat.isSelected()) {
                listDays.add(6);
            }
            if (jCheckBoxSun.isSelected()) {
                listDays.add(7);
            }

            int result = activityService.assignActivity(username, ID, listDays, time);

            leftFromUserTable();
            showUsers(listMaintainers);

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Activity assigned successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "No activity assigned!");
            }
        } catch (SQLException | UsernotFoundException | UnsuccessfulUpdateException | InvalidParameterObjectException | TimeExpiredException | ActivityAlreadyAssignedException | DayNotValidException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_jButtonAssignMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setExtendedState(AssignmentActivity.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jCheckBoxMonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxMonStateChanged
        uncheckWeekDays(1);
    }//GEN-LAST:event_jCheckBoxMonStateChanged

    private void jCheckBoxTueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxTueStateChanged
        uncheckWeekDays(2);
    }//GEN-LAST:event_jCheckBoxTueStateChanged

    private void jCheckBoxWedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxWedStateChanged
        uncheckWeekDays(3);
    }//GEN-LAST:event_jCheckBoxWedStateChanged

    private void jCheckBoxThuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxThuStateChanged
        uncheckWeekDays(4);
    }//GEN-LAST:event_jCheckBoxThuStateChanged

    private void jCheckBoxFriStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxFriStateChanged
        uncheckWeekDays(5);
    }//GEN-LAST:event_jCheckBoxFriStateChanged

    private void jCheckBoxSatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxSatStateChanged
        uncheckWeekDays(6);
    }//GEN-LAST:event_jCheckBoxSatStateChanged

    private void jCheckBoxSunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxSunStateChanged
        uncheckWeekDays(7);
    }//GEN-LAST:event_jCheckBoxSunStateChanged

    private void jButtonAssignedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignedActionPerformed

    }//GEN-LAST:event_jButtonAssignedActionPerformed

    private void jButtonAssignedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssignedMouseClicked
        setVisible(false);
        ViewAssignedActivities assignedActivities = new ViewAssignedActivities();
        assignedActivities.setVisible(true);
    }//GEN-LAST:event_jButtonAssignedMouseClicked

    private void jCheckBoxSunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSunActionPerformed

    private void jCheckBoxWedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxWedActionPerformed

    /**
     * This method takes all the skills required by the maintenance activity to
     * show them in the appropriate table.
     * 
     * @throws InvalidParameterObjectException 
     */
    private void showSkillsNeeded() throws InvalidParameterObjectException {

        try {
            skills = competence.getAllSkills(ID);
        } catch (SQLException ex) {
            Logger.getLogger(AssignmentActivity.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.showActivitySkills(skills);
    }

    /**
     * Fills the required skill table for the activity to be assigned.
     *
     * @param list: a list containing all the skills of an activity
     */
    private void showActivitySkills(List<Competence> list) {

        DefaultTableModel skills = (DefaultTableModel) jTableSkills.getModel();

        for (int i = 0; i < list.size(); i++) {
            Object column[] = new Object[1];
            column[0] = list.get(i).getDescription();
            skills.addRow(column);
        }
   
    }

    /**
     * The table cell renderer allows the coloring of the cells of the input
     * table based on their value; the coloring emphasizes the availability of
     * each maintainer.
     *
     * @param table: a JTable whose cells must be colored
     * @param column: the column of the table where the values must be checked
     */
    private void changeTable(JTable table, int column) {
        table.getColumnModel().getColumn(column).setCellRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                int st_val = Integer.parseInt(table.getValueAt(row, column).toString());

                if (st_val < 40) {
                    c.setBackground(Color.RED);
                    setText(String.valueOf(st_val) + "%");
                } else if (st_val >= 40 && st_val <= 70) {
                    c.setBackground(Color.YELLOW);
                    setText(String.valueOf(st_val) + "%");
                } else {
                    c.setBackground(Color.GREEN);
                    setText(String.valueOf(st_val) + "%");
                }

                return c;
            }
        });
    
    }
    
    /**
     * Fill a table with the maintainers contained in the list.
     * 
     * @param list:  a list containing all the maintainers
     * @throws SQLException
     * @throws UsernotFoundException
     * @throws DayNotValidException 
     */
    private void showUsers(List<UserModel> list) 
            throws SQLException, UsernotFoundException, DayNotValidException {

        DefaultTableModel users = (DefaultTableModel) jTableMaintainersAvail.getModel();
        Object column[] = new Object[9];

        for (int i = 0; i < list.size(); i++) {
            column[0] = list.get(i).getUsername();
            // Count the common skills shared between Maintainers and the activity
            // to be assigned
            column[1] = competence.getCommonSkills(skills, list.get(i).getUsername());
            // Insert the daily avaiabilities for each maintainer
            column[2] = activityService.getDailyAvailability(list.get(i).getUsername(), 1);
            column[3] = activityService.getDailyAvailability(list.get(i).getUsername(), 2);
            column[4] = activityService.getDailyAvailability(list.get(i).getUsername(), 3);
            column[5] = activityService.getDailyAvailability(list.get(i).getUsername(), 4);
            column[6] = activityService.getDailyAvailability(list.get(i).getUsername(), 5);
            column[7] = activityService.getDailyAvailability(list.get(i).getUsername(), 6);
            column[8] = activityService.getDailyAvailability(list.get(i).getUsername(), 7);

            users.addRow(column);
        }
    }

    /**
     * Remove all maintainers from the table; this method is useful for
     * refreshing the table after an activity assignment.
     */
    private void leftFromUserTable() {

        DefaultTableModel users = (DefaultTableModel) jTableMaintainersAvail.getModel();

        int length = users.getRowCount();

        for (int i = 0; i < length; i++) {
            users.removeRow(0);
        }

    }

    /**
     * Get current week number in order to fill in the appropriate label.
     *
     * @return a string that indicates the current week
     */
    private String getCurrentWeek() {
        Calendar calendar = new GregorianCalendar();
        Date trialTime = new Date();
        calendar.setTime(trialTime);
        return String.valueOf(calendar.get(Calendar.WEEK_OF_YEAR));
    }

    /**
     * This method inserts the maintainers' availabilities, for each day of the
     * week, in the input hashmap.
     */
    private void initMapIdDays() {

        for (UserModel user : listMaintainers) {
            mapIdDays.put(user.getUsername(), new ArrayList<>());
        }
    }

    /**
     * Useful method to quickly fill the label that saves the information of the
     * MaintenanceActivity to be assigned.
     * 
     * @return a string that indicates ID, area, type and time of a Maintenance
     * Activity
     */
    private String showInfo() {

        return ID + "-" + area + "-" + type + "-" + time;
    }

    /**
     * This method extracts all the maintainers from the DB and inserts them in
     * the listMaintainers; the list will then be passed to the showUsers
     * method.
     */
    private void getMaintainers() {

        try {
            listMaintainers = user.getAllMaintainers();
            this.showUsers(listMaintainers);
        } catch (SQLException | UsernotFoundException | DayNotValidException ex) {
            Logger.getLogger(AssignmentActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Unheck the box for the selected day of the week.
     *
     * @param day: an integer who represents the day of the week (1-7)
     */
    private void uncheckWeekDays(int day) {
        if (day != 1) {
            jCheckBoxMon.setSelected(false);
        }
        if (day != 2) {
            jCheckBoxTue.setSelected(false);
        }
        if (day != 3) {
            jCheckBoxWed.setSelected(false);
        }
        if (day != 4) {
            jCheckBoxThu.setSelected(false);
        }
        if (day != 5) {
            jCheckBoxFri.setSelected(false);
        }
        if (day != 6) {
            jCheckBoxSat.setSelected(false);
        }
        if (day != 7) {
            jCheckBoxSun.setSelected(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignmentActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignmentActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignmentActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignmentActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new AssignmentActivity(ID, area, type, time, week).setVisible(true);
            } catch (SQLException | InvalidParameterObjectException ex) {
                Logger.getLogger(AssignmentActivity.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAssign;
    private javax.swing.JButton jButtonAssigned;
    private javax.swing.JCheckBox jCheckBoxFri;
    private javax.swing.JCheckBox jCheckBoxMon;
    private javax.swing.JCheckBox jCheckBoxSat;
    private javax.swing.JCheckBox jCheckBoxSun;
    private javax.swing.JCheckBox jCheckBoxThu;
    private javax.swing.JCheckBox jCheckBoxTue;
    private javax.swing.JCheckBox jCheckBoxWed;
    private javax.swing.JLabel jLabelActivityInfo;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelCurrentWeek;
    private javax.swing.JLabel jLabelCurrentWeekNum;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelFri;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelMaintainersAvail;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelMon;
    private javax.swing.JLabel jLabelSat;
    private javax.swing.JLabel jLabelSkills;
    private javax.swing.JLabel jLabelSun;
    private javax.swing.JLabel jLabelThu;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleAct;
    private javax.swing.JLabel jLabelTitleCheck;
    private javax.swing.JLabel jLabelTue;
    private javax.swing.JLabel jLabelWed;
    private javax.swing.JLabel jLabelWeek;
    private javax.swing.JLabel jLabelWeekNum1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMaintainersAvail;
    private javax.swing.JTable jTableSkills;
    // End of variables declaration//GEN-END:variables

}
