package view;

import configuration.Exceptions.InvalidParameterObjectException;
import configuration.Exceptions.InvalidPermissionException;
import configuration.Exceptions.UnsuccessfulUpdateException;
import controller.Services.ActivityService;
import controller.Services.CompetenceService;
import controller.Services.DepartmentService;
import controller.Services.MaterialService;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.RoundRectangle2D;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Competences.Competence;
import model.Department.Department;
import model.Material.Material;

/**
 *
 * @author Group9
 */
public class CreateActivity extends javax.swing.JFrame {

    private List<Department> depList = new LinkedList<>();
    private List<Material> materials = new LinkedList<>();
    private DepartmentService dep = DepartmentService.getDepartmentService();
    private ActivityService act = ActivityService.getActivityService();
    private CompetenceService compService = CompetenceService.getCompetenceService();
    private MaterialService matService = MaterialService.getMaterialService();

    /**
     * Creates new form CreateActivity.
     */
    public CreateActivity() {
        initComponents();

        ImageIcon icon = new ImageIcon("src/icons/app_icon.png");
        setIconImage(icon.getImage());
        setTitle("Maintenance System App");
        setSize(1175, 630);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
            }
        });

        getAllSkills();
        getDepartments();
        getAllMaterials();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldType = new javax.swing.JTextField();
        jTextFieldDescription = new javax.swing.JTextField();
        jTextFieldTime = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelCreate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableToAssociate = new javax.swing.JTable();
        jButtonAddSkill = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAssociated = new javax.swing.JTable();
        jLabelTitleSkillsToAssign = new javax.swing.JLabel();
        jLabelTitleDep = new javax.swing.JLabel();
        jComboWeek = new javax.swing.JComboBox<>();
        jLabelWeekNum = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDepartment = new javax.swing.JTable();
        jLabelTitleSkillsAssigned = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableMaterialsToAssociate = new javax.swing.JTable();
        jLabelTitleMaterialsToAssign = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMaterialsAssociated = new javax.swing.JTable();
        jLabelMaterialsAssigned = new javax.swing.JLabel();
        jButtonAddMAterial = new javax.swing.JButton();
        jButtonRemove1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back_button.png"))); // NOI18N
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jLabelExit.setText("jLabel2");
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("CREATE ACTIVITY");

        jLabelType.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelType.setForeground(new java.awt.Color(255, 255, 255));
        jLabelType.setText("Type");

        jLabelDescription.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescription.setText("Description");

        jLabelTime.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTime.setText("Time");

        jLabelCreate.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCreate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_button.png"))); // NOI18N
        jLabelCreate.setText("Create");
        jLabelCreate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 0), new java.awt.Color(255, 204, 0), null, null));
        jLabelCreate.setOpaque(true);
        jLabelCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCreateMouseClicked(evt);
            }
        });

        jTableToAssociate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableToAssociate);

        jButtonAddSkill.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonAddSkill.setText("Add");
        jButtonAddSkill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddSkillMouseClicked(evt);
            }
        });

        jButtonRemove.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonRemove.setText("Remove");
        jButtonRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoveMouseClicked(evt);
            }
        });

        jTableAssociated.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableAssociated);

        jLabelTitleSkillsToAssign.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTitleSkillsToAssign.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleSkillsToAssign.setText("Skills To Assign");

        jLabelTitleDep.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTitleDep.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleDep.setText("Department");

        jComboWeek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52" }));

        jLabelWeekNum.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelWeekNum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWeekNum.setText("Week Number");

        jTableDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableDepartment);

        jLabelTitleSkillsAssigned.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTitleSkillsAssigned.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleSkillsAssigned.setText("Skills Assigned");

        jLabelMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        jTableMaterialsToAssociate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableMaterialsToAssociate);

        jLabelTitleMaterialsToAssign.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelTitleMaterialsToAssign.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleMaterialsToAssign.setText("Materials To Assign ");

        jTableMaterialsAssociated.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableMaterialsAssociated);

        jLabelMaterialsAssigned.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelMaterialsAssigned.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaterialsAssigned.setText("Materials Assigned ");

        jButtonAddMAterial.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonAddMAterial.setText("Add");
        jButtonAddMAterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddMAterialMouseClicked(evt);
            }
        });

        jButtonRemove1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonRemove1.setText("Remove");
        jButtonRemove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemove1MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(354, 354, 354)
                .add(jLabelTitle)
                .add(0, 0, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(35, 35, 35)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelTitleSkillsAssigned)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jButtonRemove)
                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 736, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(37, 37, 37)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jPanel2Layout.createSequentialGroup()
                                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabelType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(jTextFieldType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(60, 60, 60)
                                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jTextFieldDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(jLabelDescription))
                                                .add(60, 60, 60)
                                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabelTime)
                                                    .add(jTextFieldTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabelTitleSkillsToAssign))
                                        .add(54, 54, 54)
                                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabelWeekNum)
                                            .add(jComboWeek, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 231, Short.MAX_VALUE))
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jPanel2Layout.createSequentialGroup()
                                                .add(0, 0, Short.MAX_VALUE)
                                                .add(jButtonRemove1))
                                            .add(jPanel2Layout.createSequentialGroup()
                                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 255, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonAddSkill))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(jLabelMaterialsAssigned)
                                                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                        .add(jButtonAddMAterial)
                                                        .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                    .add(jLabelTitleMaterialsToAssign))))
                                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanel2Layout.createSequentialGroup()
                                                .add(56, 56, 56)
                                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jLabelTitleDep)
                                                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                            .add(jPanel2Layout.createSequentialGroup()
                                                .add(145, 145, 145)
                                                .add(jLabelCreate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabelMinimize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .add(jLabelExit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabelExit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelMinimize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(95, 95, 95)
                                .add(jLabelType))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelTitle)
                                .add(18, 18, 18)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabelTime)
                                    .add(jLabelWeekNum))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextFieldType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jComboWeek, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(97, 97, 97)
                        .add(jLabelDescription)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(52, 52, 52)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabelTitleSkillsToAssign)
                            .add(jLabelTitleMaterialsToAssign))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jButtonAddSkill)
                                    .add(jButtonAddMAterial))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabelTitleSkillsAssigned)
                                    .add(jLabelMaterialsAssigned))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(3, 3, 3)
                                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(93, 93, 93)
                                .add(jLabelCreate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButtonRemove)
                            .add(jButtonRemove1)))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(60, 60, 60)
                        .add(jLabelTitleDep)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelBack)
                .add(109, 109, 109)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelBack)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked
        setVisible(false);
        ManagementActivityArea activityArea = new ManagementActivityArea();
        activityArea.setVisible(true);
    }//GEN-LAST:event_jLabelBackMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCreateMouseClicked

        String type = jTextFieldType.getText();
        String description = jTextFieldDescription.getText();

        Integer time;
        try {
            time = Integer.parseInt(jTextFieldTime.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        Integer week_num = Integer.parseInt(jComboWeek.getSelectedItem().toString());

        // Avoid empty selections
        if (jTableDepartment.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Please, select a department first");
            return;
        }
        int row = jTableDepartment.getSelectedRow();
        Department department = new Department(jTableDepartment.getModel().getValueAt(row, 0).toString());

        ArrayList<Competence> skills = new ArrayList<>();
        DefaultTableModel modelC = (DefaultTableModel) jTableAssociated.getModel();

        /*
        * Add all the selected skills in the List, in order to use them for 
        * the MaintenanceActivity creation
         */
        for (int i = 0; i < modelC.getRowCount(); i++) {
            Integer id = Integer.parseInt(modelC.getValueAt(i, 0).toString());
            String descriptionSkill = modelC.getValueAt(i, 1).toString();

            Competence c = new Competence(id, descriptionSkill);
            skills.add(c);
        }

        if (skills.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please, select almost a skill to assign");
            return;
        }

        ArrayList<Material> material = new ArrayList<>();
        DefaultTableModel modelM = (DefaultTableModel) jTableMaterialsAssociated.getModel();

        /*
        * Add all the selected materials in the List, in order to use them for 
        * the MaintenanceActivity creation. It is possible to create a 
        * MaintenanceActivity without any material
         */
        for (int i = 0; i < modelM.getRowCount(); i++) {
            String typeMaterial = modelM.getValueAt(i, 0).toString();

            Material m = new Material(typeMaterial);
            material.add(m);
        }

        try {
            act.insertActivity(type, description, time, skills, material, week_num, department);
            JOptionPane.showMessageDialog(null, "Activity created successfully!");
        } catch (SQLException | UnsuccessfulUpdateException | InvalidPermissionException | InvalidParameterObjectException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jLabelCreateMouseClicked

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed

    }//GEN-LAST:event_jButtonRemoveActionPerformed


    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        this.setExtendedState(CreateActivity.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jButtonAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdd1ActionPerformed

    }//GEN-LAST:event_jButtonAdd1ActionPerformed

    private void jButtonRemove1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemove1MouseClicked
        // Avoid empty selections
        if (jTableMaterialsAssociated.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Select a material first!");
            return;
        }

        int posAssociated = jTableMaterialsAssociated.getSelectedRow();

        if (posAssociated >= 0) {

            String type = jTableMaterialsAssociated.getModel().getValueAt(posAssociated, 0).toString();

            DefaultTableModel model = (DefaultTableModel) jTableMaterialsToAssociate.getModel();
            Object column[] = new Object[1];

            column[0] = type;

            model.addRow(column);

            DefaultTableModel modelAssociated = (DefaultTableModel) jTableMaterialsAssociated.getModel();
            modelAssociated.removeRow(posAssociated);
        }
        
    }//GEN-LAST:event_jButtonRemove1MouseClicked

    private void jButtonRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemove1ActionPerformed

    }//GEN-LAST:event_jButtonRemove1ActionPerformed

    private void jButtonAddSkillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddSkillMouseClicked
         // Avoid empty selections
        if (jTableToAssociate.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Select a skill first!");
            return;
        }

        int posToAssociate = jTableToAssociate.getSelectedRow();
        // Transfer the selected skill in the Associated table
        if (posToAssociate >= 0) {

            Integer id = Integer.parseInt(jTableToAssociate.getModel().getValueAt(posToAssociate, 0).toString());
            String description = jTableToAssociate.getModel().getValueAt(posToAssociate, 1).toString();

            DefaultTableModel model = (DefaultTableModel) jTableAssociated.getModel();
            Object column[] = new Object[2];

            column[0] = id;
            column[1] = description;

            model.addRow(column);

            DefaultTableModel modelToAssociate = (DefaultTableModel) jTableToAssociate.getModel();
            // Update the ToAssociate table
            modelToAssociate.removeRow(posToAssociate);
        }
        
    }//GEN-LAST:event_jButtonAddSkillMouseClicked

    private void jButtonAddMAterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMAterialMouseClicked
        
        if (jTableMaterialsToAssociate.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Select a material first!");
            return;
        }

        int posToAssociate = jTableMaterialsToAssociate.getSelectedRow();
        // Transfer the selected material in the Associated table
        if (posToAssociate >= 0) {

            String type = jTableMaterialsToAssociate.getModel().getValueAt(posToAssociate, 0).toString();

            DefaultTableModel model = (DefaultTableModel) jTableMaterialsAssociated.getModel();
            Object column[] = new Object[1];

            column[0] = type;

            model.addRow(column);

            DefaultTableModel modelToAssociate = (DefaultTableModel) jTableMaterialsToAssociate.getModel();
           // Update the ToAssociate table
            modelToAssociate.removeRow(posToAssociate);
        }
    }//GEN-LAST:event_jButtonAddMAterialMouseClicked

    private void jButtonRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoveMouseClicked
        
        // Avoid empty selections
        if (jTableAssociated.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Select a skill first!");
            return;
        }

        int posAssociated = jTableAssociated.getSelectedRow();
        // Transfer the selected skill in the ToAssociate table
        if (posAssociated >= 0) {

            Integer id = Integer.parseInt(jTableAssociated.getModel().getValueAt(posAssociated, 0).toString());
            String description = jTableAssociated.getModel().getValueAt(posAssociated, 1).toString();

            DefaultTableModel model = (DefaultTableModel) jTableToAssociate.getModel();
            Object column[] = new Object[2];

            column[0] = id;
            column[1] = description;

            model.addRow(column);

            DefaultTableModel modelAssociated = (DefaultTableModel) jTableAssociated.getModel();
            modelAssociated.removeRow(posAssociated);
        }
        
    }//GEN-LAST:event_jButtonRemoveMouseClicked

    /**
     * This method extracts all the departments from the DB and inserts them in
     * the depList; the list will then be passed to the showDepartments method.
     */
    private void getDepartments() {
        try {
            depList = dep.getAllDepartments();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

        this.showDepartments(depList);
        depList = null;
    }

    /**
     * Fills the Jtable with the department contained inside the list passed as an input
     *
     * @param list: a list of Department
     */
    private void showDepartments(List<Department> list) {

        DefaultTableModel departments = (DefaultTableModel) jTableDepartment.getModel();

        int length = departments.getRowCount();

        if (length != 0) {
            for (int i = 0; i < length; i++) {
                departments.removeRow(0);
            }
        }

        // Fill the table
        for (int i = 0; i < list.size(); i++) {
            Object column[] = new Object[1];
            column[0] = list.get(i).getArea();

            departments.addRow(column);
        }
    }

    /**
     * This method extracts all the competences from the DB and inserts them in
     * a list; the list will be used to fill a table.
     */
    private void getAllSkills() {

        try {
            List<Competence> competences = compService.getAllCompetences();
            DefaultTableModel model = (DefaultTableModel) jTableToAssociate.getModel();

            for (Competence c : competences) {

                Object[] column = new Object[2];
                column[0] = c.getId();
                column[1] = c.getDescription();

                model.addRow(column);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }

    /**
     * This method extracts all the materials from the DB and inserts them in a
     * list; the list will be used to fill a table.
     */
    private void getAllMaterials() {

        try {

            materials = matService.getAllMaterials();
            DefaultTableModel model = (DefaultTableModel) jTableMaterialsToAssociate.getModel();

            for (Material m : materials) {

                Object[] column = new Object[1];
                column[0] = m.getType();

                model.addRow(column);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreateActivity().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddMAterial;
    private javax.swing.JButton jButtonAddSkill;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonRemove1;
    private javax.swing.JComboBox<String> jComboWeek;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelCreate;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMaterialsAssigned;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleDep;
    private javax.swing.JLabel jLabelTitleMaterialsToAssign;
    private javax.swing.JLabel jLabelTitleSkillsAssigned;
    private javax.swing.JLabel jLabelTitleSkillsToAssign;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelWeekNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableAssociated;
    private javax.swing.JTable jTableDepartment;
    private javax.swing.JTable jTableMaterialsAssociated;
    private javax.swing.JTable jTableMaterialsToAssociate;
    private javax.swing.JTable jTableToAssociate;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldTime;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables

}
